project:
  type: book

book:
  title: "Quarto Book"
  subtitle: "A KOMA-Script example"
  author: "Author, Frances I.R.S.T, and Coauthor, Second T.O."
  date: "6/22/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
      # light: flatly
      # dark: darkly
    highlight-style: default
    code-background: true
    code-fold: true
    code-summary: "Show the code"
  pdf:
    documentclass: scrbook
    papersize: a4
    # geometry:
    #   - showframe
    include-in-header: latex/preamble.tex
    include-before-body: latex/before_body.tex
    include-after-body: latex/after_body.tex
    keep-tex: false
  epub:
    cover-image: images/cover.png
  # docx:
  #   toc: true
  #   number-sections: true
  #   highlight-style: default

execute:
  warning: false

jupyter: python3
