project:
  type: book
  # output-dir: docs

book:
  title: "Quarto Book"
  subtitle: "A KOMA-Script example"
  author: "Author, Frances I.R.S.T, and Coauthor, Second T.O."
  date: "6/28/2022"
  cover-image: images/cover.png
  site-url: https://rstudio-education.github.io/hopr/
  repo-url: https://github.com/jjallaire/hopr/
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  number-sections: true
  chapters:
    - index.qmd
    - part: "Week 1"
      chapters:
        - intro.qmd
    - part: "Week 2"
      chapters:
        - summary.qmd
    - bibliography.qmd
    - sessionInfo.qmd

bibliography:
  - latex/bibliography.bib
csl: latex/chemometrics-and-intelligent-laboratory-systems.csl

format:
  html:
    theme: cosmo
    # theme:
    #   light: flatly
    #   dark: darkly
    highlight-style: default
    cover-image: images/cover.png
    code-background: true
    code-fold: false
    # code-summary: "Show the code"
    code-link: true
  pdf:
    documentclass: scrbook
    # geometry:
    #   - showframe
    include-in-header: latex/preamble.tex
    include-before-body: latex/before_body.tex
    include-after-body: latex/after_body.tex
    toc: true
    toc-depth: 3
    toc-title: Contents
    keep-tex: false
    subject: "test"
    keywords:
      - "keyword 1"
      - "keyword 2"
      - "keyword 3"
  epub:
    cover-image: images/cover.png
  # docx:
  #   toc: true
  #   number-sections: true
  #   highlight-style: default

execute:
  warning: false

# jupyter: python3
